config/routes.rb
Rails.application.routes.draw do

  resources :users, except:[:new]
  resources :articles

  root 'pages#home'
  get "about", to: "pages#about"
  get 'signup', to: 'users#new'
  get 'login', to: "session#new"
  post 'login',to: "session#create"
  get 'logout', to: 'session#destroy'
  resources :categories, except: [:destroy]

end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title , presence: true, length: {minimum: 2, maximum: 100}
  validates :description, presence: true, length: {minimum: 2, maximum: 300}


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :require_user,except: [:show,:index]
  before_action :require_same_user,only: [:edit,:update,:destroy]
  # before_action :authenticate_users!, except: %i[show index]

  # GET /articles or /articles.json
  def index

    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show

  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
    @articles = Article.find(params[:id])
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = current_users
    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

  # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description,category_ids: [])
    end

    def require_same_user

      if current_users != @article.user && !current_users.admin?
        flash[:alert] = "You can only edit or delete your own article"
        redirect_to @article
      end

    end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div id="page-content">

  <% @articles.each do |article| %>
    <div class="container">
      <div class="card text-center img-fluid rounded-4 shadow-2-strong">

        <div class="card-header">
            <% if article.user %>
              <%=  link_to article.user.username, users_path(article.user),class:"btn btn-dark btn-rounded" %>
            <% end %>

           <div class="container">
             <% if article.categories.any? %>
               <div class="mt-2 btn btn-info btn-rounded"> <%= render article.categories %></div>
             <% end %>
           </div>


        </div>

        <div class="card-body">

          <h5 class="card-title"><%= link_to article.title,article_path(article),class:"text-success" %></h5>
          <p class="card-text"><%= truncate(article.description,length: 100) %></p>

          <%= link_to "View", article_path(article),class:"btn btn-outline-success" %>
            <% if logged_in? && (article.user == current_users || current_users.admin?) %>
                <%= link_to "Edit", edit_article_path(article),class:"btn btn-outline-info" %>
                <%= button_to "Delete", article_path(article),method: :delete, data: { confirm: "Are you sure?" },class:"btn btn-outline-danger" %>
            <% end %>
            </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(article.created_at) %>ago,
            edited <%= time_ago_in_words(article.updated_at) %> ago </small>
        </div>
      </div>
    </div>

  <% end %>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <div class="container">
    <form id="info">
      <%= render "shared/errors", obj:@article %>
      <!-- Name input -->
      <div class="form-outline mb-4">
        <label class="form-label" for="form4Example1">Title</label>
        <%= form.text_field :title, placeholder: "Title of article", class: "form-control" %>
      </div>


        <div class="form-outline mb-4">
          <label class="form-label" for="form4Example3">Description</label>
          <%= form.text_area :description, placeholder: "Description", class: "form-control" %>
        </div>

        <div class="form-outline mb-4">
          <label class="form-label" for="form4Example3">Category</label>
          <%= form.collection_select :category_ids, Category.all, :id, :name,
              {prompt: "Make your selection from the list below"}, {multiple: true,size: 3, class: "form-control"} %>


        </div>

        <div class="form group row justify-content-center">
          <p><%= form.button :submit, class:"btn btn-success btn-block mb-4", params:{article:{active: true}} %> </p>
        </div>

    </form>
      <div class="mb-3">
          <%= link_to "Cancel and return to articles listing ", articles_path, class:"text-info"%>
      </div>
    </div>

<% end %>

app/views/articles/edit.html.erb
<div id="page-content">
  <h1 class="text-center mt-4">Edit article</h1>

  <%= render "articles/form", article: @article %>

  <br>

  <div>
    <%= link_to "Show this article", @article %> |
    <%= link_to "Back to articles", articles_path %>
  </div>
</div>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing all articles</h1>


<%= render 'articles/article' %>

app/views/articles/new.html.erb
<div id="page-content">
  <h1 class="text-center mt-4">Create New article</h1>

  <%= render "articles/form", article: @article %>

</div>

app/views/articles/show.html.erb
<div id="page-content">
  <h2 class="text-center mt-4"><%= @article.title %></h2>

  <div class="container">
    <div class="card text-center img-fluid rounded-4 shadow-2-strong">
      <div class="card-header">Miltos</div>
      <div class="card-body">
        <% if @article.categories.any? %>
          <%= render @article.categories %>
          <% end %>
        <p class="card-text"><%= simple_format(@article.description) %></p>
        <% if logged_in? && (@article.user == current_users || current_users.admin?) %>
          <%= link_to "Edit", edit_article_path(@article),class:"btn btn-outline-info" %>
          <%= link_to "Delete", article_path(@article),class:"btn btn-outline-danger",method: :delete, data: { confirm: "Are you sure?" } %>
      <% end %>
          </div>
      <small>Created <%= time_ago_in_words(@article.created_at) %>ago,
        edited <%= time_ago_in_words(@article.updated_at) %> ago </small>
    </div>
  </div>
</div>