config/routes.rb
Rails.application.routes.draw do

  resources :users, except:[:new]
  resources :articles

  root 'pages#home'
  get "about", to: "pages#about"
  get 'signup', to: 'users#new'
  get 'login', to: "session#new"
  post 'login',to: "session#create"
  get 'logout', to: 'session#destroy'
  resources :categories, except: [:destroy]

end

app/views/layouts/_footer.html.erb
<footer class="bg-dark text-center text-white fixed-bottom">
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2020 Copyright:
    <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name,msg|%>
  <div class="alert alert-success alert-dismissible fade show" role="alert">

    <ul>


        <%= msg %>


  </ul>


  </div>


<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to "Alpha blog",root_path, class:"navbar-brand",id:"logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu">
            <%= link_to "View Articles",articles_path,class:"dropdown-item" %>
            <% if logged_in? %>
              <%= link_to "Create you article",new_article_path,class:"dropdown-item" %>
            <% end %>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
             Categories
          </a>
          <ul class="dropdown-menu">
            <%= link_to "View Categories",categories_path,class:"dropdown-item" %>
            <% if logged_in? && current_users.admin? %>
              <%= link_to "Create category",new_category_path,class:"dropdown-item" %>
            <% end %>

          </ul>
        </li>

        <li class="nav-item">
          <%= link_to "App users",users_path, class:"nav-link" %>
        </li>

        <% if logged_in? %>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%=  '(Admin)'if current_users.admin? %> Profile [<%= current_users.username %>]
            </a>

            <ul class="dropdown-menu">
              <%= link_to "View your profile",user_path(current_users),class:"dropdown-item" %>
              <%= link_to "Edit your profile",edit_user_path(current_users),class:"dropdown-item" %>
              <%= button_to "Delete profile",user_path(current_users),class:"dropdown-item text-danger",method: :delete,data: {confirm: "Are you sure?" } %>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>

              <li class="nav-item">
                <%= link_to "Logout",logout_path, class:"nav-link", method: :delete %>
              </li>

          <% else %>

              <li class="nav-item">
                <%= link_to "Login",login_path, class:"nav-link" %>
              </li>

              <li class="nav-item">
                <%= link_to "Sign up",signup_path, class:"nav-link" %>
              </li>

        <% end %>

      </ul>



      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
      rel="stylesheet"
      />
    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
      rel="stylesheet"
      />
    <!-- MDB -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.1.0/mdb.min.css"
      rel="stylesheet"
      />    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <title>Introduction</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "custom" %>
    <%= javascript_importmap_tags %>

  </head>
  <body class="bg-color">

    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>


    <%= yield %>
  <%= render '/layouts/footer' %>
  </body>
</html>